### ISSUE TITLE
[IDEA] Add options to hide result types

### ISSUE THREAD

**Issue by BlakesHeaven** [anaggh/broken-link-checker#6]
Hi, Thank you, this is a very useful plugin.
One would hope that most links on any site are good. It would be nice to optionally hide good links so that only the problem ones are shown. Also, most of my so highlighted problem links are good, but of the server side redirect type, 3xxx. I may wish to also hide these on occasion.

Another approach,  which may be better and serve to move good links out of imediate view would be to put the results into TABS by type (4xx, 3xx, Good) in order of worst to good.

Thanks for all you do for Bludit.

**Comment by anaggh** [comment]
Hey David, Thanks for the feedback! Will take them into consideration for the next release.

**Comment by anaggh** [comment]
I have released a new version with toggles for links. https://github.com/anaggh/broken-link-checker/archive/1.0.zip

**Comment by BlakesHeaven** [comment]
Thanks very much - I'll have a look tonight 🥇
